import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const MAIN_DOMAIN = process.env.MAIN_DOMAIN || 'absenta.id';
const isLinux = process.platform === 'linux';
const caddyfilePath = isLinux ? '/etc/caddy/Caddyfile' : path.join(__dirname, '../../Caddyfile.generated');

const PORT_EXCEPTIONS: Record<string, { backend: number; frontend: number }> = {
  'cibinong': { backend: 5006, frontend: 5176 },
  '2pwk': { backend: 5005, frontend: 5174 }
};

export async function triggerCaddySync(): Promise<void> {
  console.log('[Caddy-Sync] Starting Caddy configuration sync from PostgreSQL...');

  try {
    // 1. Fetch active licenses with WireGuard IPs from PostgreSQL
    const activeLicenses = await prisma.license.findMany({
      where: {
        isActive: 1,
        wireguardIp: { not: null }
      },
      select: {
        licenseKey: true,
        requestedSlug: true,
        wireguardIp: true,
        productId: true,
        localPort: true,
        customDomain: true
      }
    });

    console.log(`[Caddy-Sync] Loaded ${activeLicenses.length} active licenses with WireGuard IPs.`);

    const upstreams: Array<{
      slug: string;
      domains: string[];
      wireguard_ip: string;
      product_id: string;
      local_port?: number;
    }> = [];

    // Fallback/Add any licenses from database
    activeLicenses.forEach(lic => {
      if (lic.requestedSlug) {
        const slugClean = lic.requestedSlug.trim().toLowerCase();
        if (slugClean === 'www') return;

        const alreadyMapped = upstreams.some(u => u.slug.toLowerCase() === slugClean);
        if (!alreadyMapped) {
          const domains = [`${slugClean}.${MAIN_DOMAIN}`];
          if (lic.customDomain) {
            domains.push(lic.customDomain.trim().toLowerCase());
          }
          upstreams.push({
            slug: lic.requestedSlug,
            domains,
            wireguard_ip: lic.wireguardIp!,
            product_id: lic.productId,
            local_port: lic.productId === 'easy-tunnel' ? (lic.localPort || 5002) : undefined
          });
        }
      }
    });

    // 2. Generate Caddyfile content
    let caddyfile = `# Caddyfile - Generated automatically by Fastify Licensing Server
# Do not edit this file directly, it will be overwritten.

{
    email sharemovie1993@gmail.com
    on_demand_tls {
        ask http://127.0.0.1:5001/api/public/validate-domain
    }
}

# --- STATIC CENTRAL ROUTES ---

# Central Landing/Portal Page
${MAIN_DOMAIN}, www.${MAIN_DOMAIN} {
    root * /var/www/${MAIN_DOMAIN}
    file_server
    try_files {path} {path}/ /index.html
}

# Central License Server API & admin UI
api.${MAIN_DOMAIN} {
    reverse_proxy 127.0.0.1:5001
}

# Central POS System
pos.${MAIN_DOMAIN} {
    reverse_proxy 10.0.0.3:3002
}

# Catch-all web client for selected subdomains (Serving static files directly)
1pwk.${MAIN_DOMAIN}, 2krw.${MAIN_DOMAIN}, 1krw.${MAIN_DOMAIN}, 1subang.${MAIN_DOMAIN}, smkn1pld.${MAIN_DOMAIN}, 3cianjur.${MAIN_DOMAIN}, 1maniis.${MAIN_DOMAIN} {
    root * /var/www/${MAIN_DOMAIN}
    file_server
    try_files {path} {path}/ /index.html
}

# --- DYNAMIC TENANT GATEWAYS ---
`;

    upstreams.forEach(up => {
      const ports = PORT_EXCEPTIONS[up.slug.toLowerCase()] || { backend: 5002, frontend: 5174 };
      const domainListStr = up.domains.join(', ');

      if (up.product_id === 'easy-tunnel') {
        const port = up.local_port || 5002;
        const isDevVitePort = port >= 5173 && port <= 5179;
        const isHttpsPort = port === 443;
        const upstreamProtocol = (isDevVitePort || isHttpsPort) ? 'https' : 'http';
        const tlsConfig = (isDevVitePort || isHttpsPort) ? ` {
        transport http {
            tls_insecure_skip_verify
        }
    }` : '';

        caddyfile += `
# Tenant: ${up.slug} (Easy Tunnel)
${domainListStr} {
    reverse_proxy * ${upstreamProtocol}://${up.wireguard_ip}:${port}${tlsConfig}
}
`;
      } else {
        caddyfile += `
# Tenant: ${up.slug}
${domainListStr} {
    # Route backend API
    reverse_proxy /api/* http://${up.wireguard_ip}:${ports.backend}
    
    # Route frontend Vite / Web client
    reverse_proxy * http://${up.wireguard_ip}:${ports.frontend}
}
`;
      }
    });

    // Write to Caddyfile
    fs.writeFileSync(caddyfilePath, caddyfile, 'utf8');
    console.log(`[Caddy-Sync] Successfully wrote Caddy configuration to ${caddyfilePath}`);

    // 3. Reload Caddy if on Linux
    if (isLinux) {
      exec('sudo systemctl is-active caddy', (activeErr, activeStdout) => {
        const isActive = !activeErr && activeStdout.trim() === 'active';
        const reloadCmd = isActive ? 'sudo systemctl reload caddy' : 'sudo systemctl restart caddy';
        console.log(`[Caddy-Sync] Caddy service is ${isActive ? 'active' : 'inactive'}. Running: ${reloadCmd}`);
        
        exec(reloadCmd, (err, _stdout, stderr) => {
          if (err) {
            console.error('[Caddy-Sync] Failed to update Caddy service:', stderr || err.message);
          } else {
            console.log('[Caddy-Sync] Caddy service successfully updated.');
          }
        });
      });
    } else {
      console.log('[Caddy-Sync] Local environment detected. Skipping Caddy service reload.');
    }

  } catch (err: any) {
    console.error('[Caddy-Sync] Critical error during sync:', err.message);
  }
}
